// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupData() {
  return window['go']['main']['App']['BackupData']();
}

export function BatchDeleteAPIKeys(arg1) {
  return window['go']['main']['App']['BatchDeleteAPIKeys'](arg1);
}

export function BatchExportAPIKeys(arg1) {
  return window['go']['main']['App']['BatchExportAPIKeys'](arg1);
}

export function BatchImportAPIKeys(arg1) {
  return window['go']['main']['App']['BatchImportAPIKeys'](arg1);
}

export function BatchTestAPIKeys(arg1) {
  return window['go']['main']['App']['BatchTestAPIKeys'](arg1);
}

export function CopyBaseURLAudit(arg1) {
  return window['go']['main']['App']['CopyBaseURLAudit'](arg1);
}

export function CreateAPIKey(arg1) {
  return window['go']['main']['App']['CreateAPIKey'](arg1);
}

export function DisableAPIKey(arg1) {
  return window['go']['main']['App']['DisableAPIKey'](arg1);
}

export function EnableAPIKey(arg1) {
  return window['go']['main']['App']['EnableAPIKey'](arg1);
}

export function GetAPIKeyDetail(arg1) {
  return window['go']['main']['App']['GetAPIKeyDetail'](arg1);
}

export function GetCopyCredentials(arg1) {
  return window['go']['main']['App']['GetCopyCredentials'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetFilterOptions() {
  return window['go']['main']['App']['GetFilterOptions']();
}

export function ListAPIKeys(arg1) {
  return window['go']['main']['App']['ListAPIKeys'](arg1);
}

export function ListAuditLogs(arg1) {
  return window['go']['main']['App']['ListAuditLogs'](arg1);
}

export function RestoreData() {
  return window['go']['main']['App']['RestoreData']();
}

export function TestAPIKey(arg1) {
  return window['go']['main']['App']['TestAPIKey'](arg1);
}

export function UpdateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1, arg2);
}
