// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BackupData():Promise<model.BackupRestoreResult>;

export function BatchDeleteAPIKeys(arg1:model.BatchDeleteAPIKeysInput):Promise<model.BatchDeleteAPIKeysResult>;

export function BatchExportAPIKeys(arg1:model.BatchExportAPIKeysInput):Promise<model.BatchExportAPIKeysResult>;

export function BatchImportAPIKeys(arg1:model.BatchImportAPIKeysInput):Promise<model.BatchImportAPIKeysResult>;

export function BatchTestAPIKeys(arg1:model.BatchTestAPIKeysInput):Promise<model.BatchTestAPIKeysResult>;

export function CopyBaseURLAudit(arg1:number):Promise<void>;

export function CreateAPIKey(arg1:model.CreateAPIKeyInput):Promise<model.APIKey>;

export function DisableAPIKey(arg1:number):Promise<model.APIKey>;

export function EnableAPIKey(arg1:number):Promise<model.APIKey>;

export function GetAPIKeyDetail(arg1:number):Promise<model.APIKeyDetail>;

export function GetCopyCredentials(arg1:number):Promise<string>;

export function GetDashboardStats():Promise<model.DashboardStats>;

export function GetFilterOptions():Promise<model.FilterOptions>;

export function ListAPIKeys(arg1:model.APIKeyFilter):Promise<model.APIKeyListResult>;

export function ListAuditLogs(arg1:number):Promise<Array<model.AuditLog>>;

export function RestoreData():Promise<model.BackupRestoreResult>;

export function TestAPIKey(arg1:number):Promise<model.APIKeyDetail>;

export function UpdateAPIKey(arg1:number,arg2:model.UpdateAPIKeyInput):Promise<model.APIKey>;
